name: dio_more
description: >
  A developer toolkit built on top of Dio providing structured visual console logging
  and type-safe API endpoint registry management.
version: 0.9.0
homepage: https://github.com/Aspire5/dio_more
repository: https://github.com/Aspire5/dio_more
issue_tracker: https://github.com/Aspire5/dio_more/issues

topics:
  - dio
  - logging
  - debugging
  - http
  - network

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.8.0+1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
